# Generated by Django 2.2 on 2021-04-29 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('goods_xinghao', models.CharField(max_length=20, verbose_name='商品型号')),
                ('goods_price', models.IntegerField(verbose_name='商品价格')),
                ('goods_inventory', models.IntegerField(verbose_name='库存')),
                ('goods_produceddate', models.DateField(default=django.utils.timezone.now, verbose_name='生产日期')),
                ('goods_img', models.ImageField(default='1.jpg', upload_to='', verbose_name='商品图片')),
                ('goods_remark', models.CharField(max_length=255, verbose_name='商品备注')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='goodstype',
            fields=[
                ('fenlei_id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类编号')),
                ('fenlei', models.SmallIntegerField()),
                ('fenlei_name', models.CharField(max_length=10, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=20)),
                ('manager_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='salesman',
            fields=[
                ('salesman_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品名称')),
                ('salesman_name', models.CharField(max_length=10, verbose_name='名字')),
                ('salesman_number', models.BigIntegerField(verbose_name='手机号')),
                ('salesman_hiredate', models.DateField(auto_now_add=True, verbose_name='入职时间')),
                ('salesman_ordernumber', models.IntegerField(verbose_name='销量')),
                ('salesman_img', models.ImageField(upload_to='', verbose_name='销售图片')),
                ('salesman_sex', models.CharField(choices=[('女性', '女'), ('男性', '男')], default='女性', max_length=10, verbose_name='销售性别')),
            ],
            options={
                'verbose_name': '销售',
                'verbose_name_plural': '销售',
            },
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False, verbose_name='经销商编号')),
                ('supplier_name', models.CharField(max_length=20, verbose_name='名称')),
                ('supplier_address', models.CharField(max_length=20, verbose_name='地址')),
                ('supplier_number', models.BigIntegerField(verbose_name='手机号')),
                ('supplier_date', models.DateField(default=django.utils.timezone.now, verbose_name='合作时间')),
            ],
            options={
                'verbose_name': '经销商',
                'verbose_name_plural': '经销商',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, verbose_name='用户名称')),
                ('user_number', models.BigIntegerField(verbose_name='用户手机号')),
                ('user_brithday', models.DateField(default=django.utils.timezone.now, verbose_name='用户生日')),
                ('user_create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_mail', models.EmailField(max_length=256, verbose_name='用户邮箱')),
                ('user_sex', models.CharField(choices=[('女性', '女'), ('男性', '男')], default='女性', max_length=10, verbose_name='用户性别')),
                ('username', models.IntegerField(verbose_name='账号')),
                ('userpassword', models.CharField(max_length=10, verbose_name='密码')),
                ('user_address', models.CharField(max_length=50, verbose_name='地址')),
                ('user_img', models.ImageField(upload_to='', verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order_salestime', models.DateTimeField(verbose_name='销售时间')),
                ('order_remark', models.TextField(verbose_name='订单备注')),
                ('goods_number', models.IntegerField(verbose_name='商品数量')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodAname', to='Ftapp.goods', verbose_name='商品名称')),
                ('salesman_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nm', to='Ftapp.salesman', verbose_name='销售名字')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSname', to='Ftapp.user', verbose_name='用户名字')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='fenlei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type1', to='Ftapp.goodstype', verbose_name='商品分类'),
        ),
    ]
