# Generated by Django 2.2 on 2021-04-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ftapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_date',
        ),
    ]
