# Generated by Django 2.2 on 2021-04-29 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ftapp', '0003_supplier_supplier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goods_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goodid', to='Ftapp.goods', verbose_name='商品名称'),
            preserve_default=False,
        ),
    ]
