# Generated by Django 2.2 on 2021-04-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ftapp', '0004_order_goods_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goods_id',
        ),
    ]
