# Generated by Django 2.2 on 2021-05-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ftapp', '0008_user_user_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_sessions',
        ),
        migrations.AddField(
            model_name='supplier',
            name='goods_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gm', to='Ftapp.goods', verbose_name='合作产品'),
            preserve_default=False,
        ),
    ]
