# Generated by Django 2.2 on 2021-05-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ftapp', '0009_auto_20210509_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_remark_img',
            field=models.ImageField(default=1, upload_to='', verbose_name='备注图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_salesmoney',
            field=models.CharField(default=1, max_length=100, verbose_name='销售金额'),
            preserve_default=False,
        ),
    ]
