# Generated by Django 2.2 on 2021-05-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ftapp', '0010_auto_20210510_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '合作商', 'verbose_name_plural': '合作商'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='goods_name',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='合作机构编号'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=20, verbose_name='合作机构名称'),
        ),
    ]
