# Generated by Django 2.2 on 2021-05-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ftapp', '0011_auto_20210510_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='goods_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='gm', to='Ftapp.goods', verbose_name='合作产品'),
            preserve_default=False,
        ),
    ]
